version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/devtrackr
      - SPRING_PROFILES_ACTIVE=dev
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - devtrackr-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - devtrackr-network

networks:
  devtrackr-network:
    driver: bridge

volumes:
  mongo-data: